<?php return array(
    'root' => array(
        'name' => 'yiisoft/yii2-app-advanced',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => 'b9d29c4d521d400042c928652fa3b7beebc8939e',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '2amigos/yii2-tinymce-widget' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'a58b7a59a1508f4251a8cea9e010d31c9733bde4',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../2amigos/yii2-tinymce-widget',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'almasaeed2010/adminlte' => array(
            'pretty_version' => 'v2.4.18',
            'version' => '2.4.18.0',
            'reference' => 'e7ffa67a4649dc08d2018708a38604a6c0a02ab6',
            'type' => 'template',
            'install_path' => __DIR__ . '/../almasaeed2010/adminlte',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'behat/gherkin' => array(
            'pretty_version' => 'v4.9.0',
            'version' => '4.9.0.0',
            'reference' => '0bc8d1e30e96183e4f36db9dc79caead300beff4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../behat/gherkin',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'borales/yii2-phone-input' => array(
            'pretty_version' => '0.3.0',
            'version' => '0.3.0.0',
            'reference' => '563bfab9afed717422e1db848180c6dde706a907',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../borales/yii2-phone-input',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/bootstrap' => array(
            'pretty_version' => 'v3.4.1',
            'version' => '3.4.1.0',
            'reference' => '68b0d231a13201eb14acd3dc84e51543d16e5f7e',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/chart-js' => array(
            'pretty_version' => 'v2.9.4',
            'version' => '2.9.4.0',
            'reference' => '9bd4cf82fda9f50a5fb50b72843e06ab88124278',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/chart-js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/chart.js' => array(
            'pretty_version' => 'v4.3.0',
            'version' => '4.3.0.0',
            'reference' => '83ba8fd77689645d0f915a6c8b4881b882be5276',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/chart.js',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/inputmask' => array(
            'pretty_version' => '3.3.11',
            'version' => '3.3.11.0',
            'reference' => '5e670ad62f50c738388d4dcec78d2888505ad77b',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/inputmask',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/intl-tel-input' => array(
            'pretty_version' => 'v16.1.0',
            'version' => '16.1.0.0',
            'reference' => '52211bd88178f2cbed022b24d154ef980aef2878',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/intl-tel-input',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/jquery' => array(
            'pretty_version' => '3.6.4',
            'version' => '3.6.4.0',
            'reference' => '91ef2d8836342875f2519b5815197ea0f23613cf',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/jquery-ui' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'reference' => '44ecf3794cc56b65954cc19737234a3119d036cc',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/jquery-ui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/pdfjs-dist' => array(
            'pretty_version' => 'v2.16.105',
            'version' => '2.16.105.0',
            'reference' => 'cc3d3bf299ae11f8f72ae8d64cbf19b340f9a996',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/pdfjs-dist',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/punycode' => array(
            'pretty_version' => 'v1.3.2',
            'version' => '1.3.2.0',
            'reference' => '38c8d3131a82567bfef18da09f7f4db68c84f8a3',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/punycode',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/viewerjs' => array(
            'pretty_version' => 'v0.5.9',
            'version' => '0.5.9.0',
            'reference' => '4f6e52aaad44b4c11e5de28e40a488c0a4ccbebf',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/viewerjs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bower-asset/yii2-pjax' => array(
            'pretty_version' => '2.0.8',
            'version' => '2.0.8.0',
            'reference' => 'a9298d57da63d14a950f1b94366a864bc62264fb',
            'type' => 'bower-asset',
            'install_path' => __DIR__ . '/../bower-asset/yii2-pjax',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cebe/markdown' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '9bac5e971dd391e2802dca5400bbeacbaea9eb86',
            'type' => 'library',
            'install_path' => __DIR__ . '/../cebe/markdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'cebe/yii2-gravatar' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'c9c01bd14c9bdee9e5ae1ef1aad23f80c182c057',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../cebe/yii2-gravatar/cebe/gravatar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'codeception/codeception' => array(
            'pretty_version' => '4.2.x-dev',
            'version' => '4.2.9999999.9999999-dev',
            'reference' => 'c21e4fee784f6ae8eb2a9617b90f47cd28f82d80',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/codeception',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-asserts' => array(
            'pretty_version' => '1.13.2',
            'version' => '1.13.2.0',
            'reference' => '184231d5eab66bc69afd6b9429344d80c67a33b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-asserts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/lib-innerbrowser' => array(
            'pretty_version' => '1.5.1',
            'version' => '1.5.1.0',
            'reference' => '31b4b56ad53c3464fcb2c0a14d55a51a201bd3c2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/lib-innerbrowser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-asserts' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '59374f2fef0cabb9e8ddb53277e85cdca74328de',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-asserts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-filesystem' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => '781be167fb1557bfc9b61e0a4eac60a32c534ec1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-filesystem',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/module-yii2' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'reference' => '14269d059b8eaedf3d414a673907bd874cd4ed04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/module-yii2',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/phpunit-wrapper' => array(
            'pretty_version' => '6.8.4',
            'version' => '6.8.4.0',
            'reference' => '6267fb4e647da0e708b3aef181ff679a64433d67',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/phpunit-wrapper',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/stub' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'eea518711d736eab838c1274593c4568ec06b23d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/stub',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'codeception/verify' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'fa0bb946b6d61279f461bcc5a677ac0ed5eab9b3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../codeception/verify',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'components/flag-icon-css' => array(
            'pretty_version' => '3.5.0',
            'version' => '3.5.0.0',
            'reference' => '5141384c57972b0b08fc3bb67bea297321fbd799',
            'type' => 'component',
            'install_path' => __DIR__ . '/../components/flag-icon-css',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'diecoding/yii2-core' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'f76561ebfd122fbc3b19cee64c536f6399b388e6',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../diecoding/yii2-core',
            'aliases' => array(
                0 => '9999999-dev',
            ),
            'dev_requirement' => false,
        ),
        'diecoding/yii2-dropify' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => 'e4bb24237da2303531ee9ba2fc6b796ebad14592',
            'type' => 'library',
            'install_path' => __DIR__ . '/../diecoding/yii2-dropify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'diecoding/yii2-pdfjs' => array(
            'pretty_version' => '0.0.1',
            'version' => '0.0.1.0',
            'reference' => '6ece5db912baeacfd9b96b2efe67babc30dd7421',
            'type' => 'yii2-widget',
            'install_path' => __DIR__ . '/../diecoding/yii2-pdfjs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'diecoding/yii2-rbac' => array(
            'pretty_version' => 'v0.3.0',
            'version' => '0.3.0.0',
            'reference' => '40649baec0082a7cdb8434fe0741b43215944765',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../diecoding/yii2-rbac',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'diecoding/yii2-toastr' => array(
            'pretty_version' => 'v1.3.3',
            'version' => '1.3.3.0',
            'reference' => 'e33e05a63e413121e6937eb15442b911d0db6e09',
            'type' => 'library',
            'install_path' => __DIR__ . '/../diecoding/yii2-toastr',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dmstr/yii2-adminlte-asset' => array(
            'pretty_version' => '2.6.2',
            'version' => '2.6.2.0',
            'reference' => 'c96336e1960ebc6c1e72487a7c6ca1a1589519fe',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../dmstr/yii2-adminlte-asset',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '612a3ee5ab0d5dd97b7cf3874a6efe24325efac3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '39ab8fcf5a51ce4b85ca97c7a7d033eb12831124',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '3.2.6',
            'version' => '3.2.6.0',
            'reference' => 'e5997fa97e8790cdae03a9cbd5e78e45e3c7bda7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.16.0',
            'version' => '4.16.0.0',
            'reference' => '523407fb06eb9e5f3d59889b3978d5bfe94299c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.23.0',
            'version' => '1.23.0.0',
            'reference' => 'e3daa170d00fde61ea7719ef47bb09bb8f1d9b01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'fortawesome/font-awesome' => array(
            'pretty_version' => 'v4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'a8386aae19e200ddb0f6845b5feeee5eb7013687',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fortawesome/font-awesome',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/libphonenumber-for-php' => array(
            'pretty_version' => '8.13.14',
            'version' => '8.13.14.0',
            'reference' => '31b94ef2aa349b76bb725f375e9cfa2e398a1620',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/libphonenumber-for-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'giggsey/locale' => array(
            'pretty_version' => '2.4',
            'version' => '2.4.0.0',
            'reference' => 'a6b33dfc9e8949b7e28133c4628b29cd9f1850bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../giggsey/locale',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'graham-campbell/result-type' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '672eff8cf1d6fe1ef09ca0f89c4b287d6a3eb831',
            'type' => 'library',
            'install_path' => __DIR__ . '/../graham-campbell/result-type',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => 'b635f279edd83fc275f822a1188157ffea568ff6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'imagine/imagine' => array(
            'pretty_version' => '1.3.5',
            'version' => '1.3.5.0',
            'reference' => '7151d553edec4dc2bbac60419f7a74ff34700e7f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imagine/imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-fileinput' => array(
            'pretty_version' => 'v5.5.2',
            'version' => '5.5.2.0',
            'reference' => '35c29cd9fd5bc47eae5238feaabee95b2d7efe3c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-fileinput',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-popover-x' => array(
            'pretty_version' => 'v1.5.1',
            'version' => '1.5.1.0',
            'reference' => '36c382739c4f61ee44263a426e6447abed5ff0bd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-popover-x',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/bootstrap-star-rating' => array(
            'pretty_version' => 'v4.1.2',
            'version' => '4.1.2.0',
            'reference' => 'c301efed4c82e9d5f11a0845ae428ba60931b44e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/bootstrap-star-rating',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/dependent-dropdown' => array(
            'pretty_version' => 'v1.4.9',
            'version' => '1.4.9.0',
            'reference' => '54a8806002ee21b744508a2edb95ed01d35c6cf9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/dependent-dropdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/php-date-formatter' => array(
            'pretty_version' => 'v1.3.6',
            'version' => '1.3.6.0',
            'reference' => '514a53660b0d69439236fd3cbc3f41512adb00a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../kartik-v/php-date-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-bootstrap4-dropdown' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'reference' => 'b65783f2de8ff0733e3787c853a53e9f13bebac1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-bootstrap4-dropdown',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-date-range' => array(
            'pretty_version' => 'v1.7.3',
            'version' => '1.7.3.0',
            'reference' => '7d80d6e2598e252487fe1acf911b8cb43f45e3b1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-date-range',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-datecontrol' => array(
            'pretty_version' => 'v1.9.9',
            'version' => '1.9.9.0',
            'reference' => '88ac2401ce1858b0da98b498197373691953c3d6',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-datecontrol',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-detail-view' => array(
            'pretty_version' => 'v1.8.7',
            'version' => '1.8.7.0',
            'reference' => '0b130581bce1ff26a98750433489cdc4816080a1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-detail-view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-dialog' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '510c3a35ffe79987cde9a9366cedbff545fd92d4',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dialog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-dynagrid' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'reference' => '02956ed5c753010e700bfdb63e67ef41606e1c2d',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-dynagrid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-editable' => array(
            'pretty_version' => 'v1.8.0',
            'version' => '1.8.0.0',
            'reference' => 'ae4cc2384e667ba9dfe8bfb0098716caeb2500a8',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-editable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-export' => array(
            'pretty_version' => 'v1.4.2',
            'version' => '1.4.2.0',
            'reference' => '6b313c5af225aefcf258777d9914b940e69cea99',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-export',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-field-range' => array(
            'pretty_version' => 'v1.3.5',
            'version' => '1.3.5.0',
            'reference' => '8a18edb343b3beb96ddc86e4a06aee28be160787',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-field-range',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-grid' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '7f8c9270dde525b60960b8c4cb2d40d861b3bdb9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-grid',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-helpers' => array(
            'pretty_version' => 'v1.3.9',
            'version' => '1.3.9.0',
            'reference' => '0bec7a97bf9d0293d96be5c496fe9654c4dec94b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-helpers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-icons' => array(
            'pretty_version' => 'v1.4.8',
            'version' => '1.4.8.0',
            'reference' => '81334b3d888d4baaeb6ac458475258130474237e',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-icons',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-krajee-base' => array(
            'pretty_version' => 'v3.0.5',
            'version' => '3.0.5.0',
            'reference' => '5c095126d1be47e0bb1f92779b7dc099f6feae31',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-krajee-base',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-money' => array(
            'pretty_version' => 'v1.2.3',
            'version' => '1.2.3.0',
            'reference' => 'e656608dd32cc3aaade99af7c920362e00a42dbe',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-money',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-mpdf' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => '7ea3a5f9bcf5bcf6d681bd82cbe843c356d1428c',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-popover-x' => array(
            'pretty_version' => 'v1.3.5',
            'version' => '1.3.5.0',
            'reference' => 'b0320d1315bbfce31ec8907882c6f4abed223a28',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-popover-x',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-sortable' => array(
            'pretty_version' => 'v1.2.2',
            'version' => '1.2.2.0',
            'reference' => 'a6f9a9adb873d6345de92bbe5e436ac1a1db30bc',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-sortable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-activeform' => array(
            'pretty_version' => 'v1.6.2',
            'version' => '1.6.2.0',
            'reference' => '98dbf789c9f71a35c76a8c2b667e86815ae51ac1',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-activeform',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-affix' => array(
            'pretty_version' => 'v1.0.0',
            'version' => '1.0.0.0',
            'reference' => '2184119bfa518c285406156f744769b13b861712',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-affix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-alert' => array(
            'pretty_version' => 'v1.1.5',
            'version' => '1.1.5.0',
            'reference' => '6a45d7dc294eecd578cf8cb9acb671d1cafa0727',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-alert',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-colorinput' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => 'e35e6c7615a735b65557d6c38d112b77e2628c69',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-colorinput',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datepicker' => array(
            'pretty_version' => 'v1.4.8',
            'version' => '1.4.8.0',
            'reference' => 'f5f8b396cf03d4a383aad5e7b338f8cb065abf66',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datepicker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-datetimepicker' => array(
            'pretty_version' => 'v1.5.1',
            'version' => '1.5.1.0',
            'reference' => '85b22d38553ca207f86be198f37e6531347e9a23',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-datetimepicker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-depdrop' => array(
            'pretty_version' => 'v1.0.6',
            'version' => '1.0.6.0',
            'reference' => 'ea347e3793fbd8273cc9bd1eb94c4b32bb55d318',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-depdrop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-fileinput' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'b5500b6855526837154694c2afab8dbc3afc8abd',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-fileinput',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-growl' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => '37e8f9f10d3bc9d71f3ef64c4aaa0e2fc83dd5dc',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-growl',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-rangeinput' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'dd9019bab7e5bf570a02870d9e74387891bbdb32',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-rangeinput',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-rating' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'd3d7249490044f80e65f8f3938191f39a76586b2',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-rating',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-select2' => array(
            'pretty_version' => 'v2.2.4',
            'version' => '2.2.4.0',
            'reference' => 'f74f2cfbd5b4628ea578735890c39f9a8e4ed062',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-select2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-sidenav' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => '87e9c815624aa966d70bb4507b3d53c158db0d43',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-sidenav',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-spinner' => array(
            'pretty_version' => 'v1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'eb10dad17a107bf14f173c99994770ca23c548a6',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-spinner',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-switchinput' => array(
            'pretty_version' => 'v1.3.1',
            'version' => '1.3.1.0',
            'reference' => '7d8ee999d79bcdc1601da5cd59439ac7eb1f5ea6',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-switchinput',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-timepicker' => array(
            'pretty_version' => 'v1.0.5',
            'version' => '1.0.5.0',
            'reference' => '680aec2d79846e926c072da455cf6f33e1c3bb12',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-timepicker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-touchspin' => array(
            'pretty_version' => 'v1.2.4',
            'version' => '1.2.4.0',
            'reference' => '1eec4c3f3a8bf9a170e1e0682c2c89f2929d65e9',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-touchspin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widget-typeahead' => array(
            'pretty_version' => 'v1.0.4',
            'version' => '1.0.4.0',
            'reference' => '7b7041a3cbbeb2db0a608e9f6c9b3f4f63b0069d',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widget-typeahead',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kartik-v/yii2-widgets' => array(
            'pretty_version' => 'v3.4.1',
            'version' => '3.4.1.0',
            'reference' => 'e5a030d700243a90eccf96a070380bd3b76e17a3',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../kartik-v/yii2-widgets',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '3.3.3',
            'version' => '3.3.3.0',
            'reference' => 'c1123697f6a2ec29162b82f170dd4a491f524773',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lesha724/yii2-document-viewer' => array(
            'pretty_version' => 'v0.1.0',
            'version' => '0.1.0.0',
            'reference' => '3f8ceef2e95b5f11bc3b8a87cd44857a7d937a51',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../lesha724/yii2-document-viewer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.2.6',
            'version' => '2.2.6.0',
            'reference' => '30ad6f93cf3efe4192bc7a4c9cad11ff8f4f237f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '95c56caa1cf5c766ad6d65b6344b807c1e8405b9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '728434227fe21be27ff6d86621a1b13107a2562c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mdmsoft/yii2-admin' => array(
            'pretty_version' => '2.12',
            'version' => '2.12.0.0',
            'reference' => '10e526fbcf6350ed4cc9ba6298f887d611685367',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../mdmsoft/yii2-admin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mobiledetect/mobiledetectlib' => array(
            'pretty_version' => '2.8.41',
            'version' => '2.8.41.0',
            'reference' => 'fc9cccd4d3706d5a7537b562b59cc18f9e4c0cb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mobiledetect/mobiledetectlib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/mpdf' => array(
            'pretty_version' => 'v8.1.6',
            'version' => '8.1.6.0',
            'reference' => '146c7c1dfd21c826b9d5bbfe3c15e52fd933c90f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/mpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mpdf/psr-log-aware-trait' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '7a077416e8f39eb626dee4246e0af99dd9ace275',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mpdf/psr-log-aware-trait',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.11.1',
            'version' => '1.11.1.0',
            'reference' => '7284c22080590fb39f2ffa3e9057f10a4ddd0e0c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.4',
            'version' => '1.8.4.0',
            'reference' => 'a867478eae49c9f59ece437ae7f9506bfaa27483',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nickcv/yii2-encrypter' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => 'eaedea577f10ba605c1408cb9901e591d8034a8b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../nickcv/yii2-encrypter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/bootstrap' => array(
            'pretty_version' => '4.6.2',
            'version' => '4.6.2.0',
            'reference' => NULL,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/dropify' => array(
            'pretty_version' => '0.2.2',
            'version' => '0.2.2.0',
            'reference' => NULL,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/dropify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/jquery' => array(
            'pretty_version' => '3.7.0',
            'version' => '3.7.0.0',
            'reference' => NULL,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/jquery',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'npm-asset/toastr' => array(
            'pretty_version' => '2.1.4',
            'version' => '2.1.4.0',
            'reference' => NULL,
            'type' => 'npm-asset',
            'install_path' => __DIR__ . '/../npm-asset/toastr',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paragonie/random_compat' => array(
            'pretty_version' => 'v9.99.100',
            'version' => '9.99.100.0',
            'reference' => '996434e5492cb4c3edcb9168db6fbb1359ef965a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paragonie/random_compat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '2df402786ab5368a0169091f61a7c1e0eb6852d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'a70c0ced4be299a63d32fa96d9281d03e94041df',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.3.0',
            'version' => '5.3.0.0',
            'reference' => '622548b623e81ca6d78b721c5e029f4ce664f170',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.7.2',
            'version' => '1.7.2.0',
            'reference' => 'b2fe4d22a5426f38e014855322200b97b5362c0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpnt/yii2-chartjs' => array(
            'pretty_version' => '0.0.2',
            'version' => '0.0.2.0',
            'reference' => 'ce836c38180bc7a6509d3e96b668f7976058ed3c',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../phpnt/yii2-chartjs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpexcel' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'reference' => '1441011fb7ecdd8cc689878f54f8b58a6805f870',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpexcel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'fde2ccf55eaef7e86021ff1acce26479160a0fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpoption/phpoption' => array(
            'pretty_version' => '1.9.1',
            'version' => '1.9.1.0',
            'reference' => 'dd3a383e599f49777d8b628dadbb90cae435b87e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoption/phpoption',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'fc1156187f9f6c8395886fe85ed88a0a245d72e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'reference' => '451c3cd1418cf640de218914901e51b064abb093',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.22.0',
            'version' => '1.22.0.0',
            'reference' => 'ec58baf7b3c7f1c81b3b00617c953249fb8cf30c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '5.3.2',
            'version' => '5.3.2.0',
            'reference' => 'c89677919c5dd6d3b3852f230a663118762218ac',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'reference' => '3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '791198a2c6254db10131eecfe8c06670700904db',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '6.5.14',
            'version' => '6.5.14.0',
            'reference' => 'bac23fe7ff13dbdb461481f706f0e9fe746334b7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '5.0.10',
            'version' => '5.0.10.0',
            'reference' => 'cd1cf05c553ecfec36b170070573e540b67d3f1f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '0955afe48220520692d2d09f7ab7e0f93ffd6a31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'e616d01114759c4c489f93b099585439f795fe35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.1',
            'version' => '1.1.0.0',
            'reference' => 'cb6ce4845ce34a8ad9e68117c10ee90a29919eba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.0|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'rmrevin/yii2-fontawesome' => array(
            'pretty_version' => '2.17.1',
            'version' => '2.17.1.0',
            'reference' => '65ce306da864f4d558348aeba040ed7876878090',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../rmrevin/yii2-fontawesome',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '1de8cd5c010cb153fcd68b8d0f64606f523f7619',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => '34369daee48eafb2651bea869b4b15d75ccc35f9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '347c1d8b49c5c3ee30c7040ea6fc446790e6bddd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => 'cd0871b3975fb7fc44d11314fd1ee20925fce4f5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '3.1.5',
            'version' => '3.1.5.0',
            'reference' => '73a9676f2833b9a7c36968f9d882589cd75511e6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '3.0.4',
            'version' => '3.0.4.0',
            'reference' => 'e67f6d32ebd0c749cf9d1dbd9f226c727043cdf2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '1.1.2',
            'version' => '1.1.2.0',
            'reference' => '9b8772b9cbd456ab45d4a598d2dd1a1bced6363d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '367dcba38d6e1977be014dc4b22f47a484dac7fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/resource-operations' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/resource-operations',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '99732be0ddb3361e16ad77b68ba41efc8e979019',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'select2/select2' => array(
            'pretty_version' => '4.0.13',
            'version' => '4.0.13.0',
            'reference' => '45f2b83ceed5231afa7b3d5b12b58ad335edd82e',
            'type' => 'component',
            'install_path' => __DIR__ . '/../select2/select2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'setasign/fpdi' => array(
            'pretty_version' => 'v2.3.7',
            'version' => '2.3.7.0',
            'reference' => 'bccc892d5fa1f48c43f8ba7db5ed4ba6f30c8c05',
            'type' => 'library',
            'install_path' => __DIR__ . '/../setasign/fpdi',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sizeg/yii2-jwt' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '40fc06e8eb7fd4251639a45a0710663fc8a9558b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../sizeg/yii2-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'skeeks/yii2-mobile-detect' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '9b489bae01433806fbcda00ceb1a3809f71baa54',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../skeeks/yii2-mobile-detect',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'soundasleep/html2text' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '83502b6f8f1aaef8e2e238897199d64f284b4af3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../soundasleep/html2text',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v6.3.0',
            'version' => '6.3.0.0',
            'reference' => '8a5d5072dca8f48460fce2f4131fcc495eec654c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v4.2.4',
            'version' => '4.2.4.0',
            'reference' => '61d85c5af2fc058014c7c89504c3944e73a086f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v5.4.24',
            'version' => '5.4.24.0',
            'reference' => '560fc3ed7a43e6d30ea94a07d77f9a60b8ed0fb8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'reference' => 'da3d9da2ce0026771f5fe64cb332158f1bd2bc33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v3.4.47',
            'version' => '3.4.47.0',
            'reference' => 'ef97bcfbae5b384b4ca6c8d57b617722f15241a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v5.4.22',
            'version' => '5.4.22.0',
            'reference' => '1df20e45d56da29a4b1d8259dd6e950acbf1b13f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'reference' => 'f98b54df6ad059855739db6fcbc2d36995283fe1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '2.0',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v5.4.21',
            'version' => '5.4.21.0',
            'reference' => '078e9a5e1871fcfe6a5ce421b539344c21afef19',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '5bbc823adecdae860bb64756d639ecfec17b050a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '927013f3aac555983a5059aada98e1907d842695',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '511a08c03c1960e08a883f4cffcacd219b758354',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '639084e360537a19f9ee352433b84ce831f3d2da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '19bd1e4fcd5b91116f14d8533c57831ed00571b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '8ad114f6b39e2c98a8b0e3bd907732c207c2b534',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '869329b1e9894268a8a61dabb69153029b7a8c97',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php72',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '9e8ecb5f92152187c4799efd3c96b78ccab18ff9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.27.0',
            'version' => '1.27.0.0',
            'reference' => '7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v1.1.2',
            'version' => '1.1.2.0',
            'reference' => '191afdcb5804db960d26d8566b7e9a2843cab3a0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v5.4.22',
            'version' => '5.4.22.0',
            'reference' => '8036a4c76c0dd29e60b6a7cafcacc50cf088ea62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.4.23',
            'version' => '5.4.23.0',
            'reference' => '4cd2e3ea301aadd76a4172756296fe552fb45b0b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '34a41e998c2183e22995f158c581e7b5e755ab9e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tinymce/tinymce' => array(
            'pretty_version' => '6.5.0',
            'version' => '6.5.0.0',
            'reference' => '31251ab0bdc693efb4d510a2d0edb07d47ca355c',
            'type' => 'component',
            'install_path' => __DIR__ . '/../tinymce/tinymce',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v5.5.0',
            'version' => '5.5.0.0',
            'reference' => '1a7ea2afc49c3ee6d87061f5a233e3a035d0eae7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wbraganca/yii2-dynamicform' => array(
            'pretty_version' => 'v2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'bebb469055dc8f8f50b586eefe69d847ead7c11b',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../wbraganca/yii2-dynamicform',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.11.0',
            'version' => '1.11.0.0',
            'reference' => '11cb2199493b2f8a3b53e7f19068fc6aac760991',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2' => array(
            'pretty_version' => '2.0.48.1',
            'version' => '2.0.48.1',
            'reference' => 'de92f154eefe322fc1b1b2a52cce46677441ced4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yiisoft/yii2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-app-advanced' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => 'b9d29c4d521d400042c928652fa3b7beebc8939e',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-authclient' => array(
            'pretty_version' => '2.2.14',
            'version' => '2.2.14.0',
            'reference' => '6bd4b4efc60db2b31bb957a473442900c704857e',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-authclient',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-bootstrap' => array(
            'pretty_version' => '2.0.11',
            'version' => '2.0.11.0',
            'reference' => '83d144f4089adaa7064ad60dc4c1436daa2eb30e',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-bootstrap',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-bootstrap4' => array(
            'pretty_version' => '2.0.11',
            'version' => '2.0.11.0',
            'reference' => '6681a7ca2319499c1c35f09e803c5337e56b3dae',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-bootstrap4',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-composer' => array(
            'pretty_version' => '2.0.10',
            'version' => '2.0.10.0',
            'reference' => '94bb3f66e779e2774f8776d6e1bdeab402940510',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../yiisoft/yii2-composer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-debug' => array(
            'pretty_version' => '2.1.23',
            'version' => '2.1.23.0',
            'reference' => '73af53bd1b99d40f983ba57386ac6c374d9ef177',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-debug',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-faker' => array(
            'pretty_version' => '2.0.5',
            'version' => '2.0.5.0',
            'reference' => '8c361657143bfaea58ff7dcc9bf51f1991a46f5d',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-faker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-gii' => array(
            'pretty_version' => '2.1.4',
            'version' => '2.1.4.0',
            'reference' => 'd879cb186361fbc6f71a2d994d580b5a071a5642',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-gii',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'yiisoft/yii2-httpclient' => array(
            'pretty_version' => '2.0.15',
            'version' => '2.0.15.0',
            'reference' => '5a8350e15f2db3555ba52830c9c701587c136e87',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-httpclient',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-imagine' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '8637f63ee2eb81b7fe1f4c0e16cc8cc474a68bae',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-jui' => array(
            'pretty_version' => '2.0.7',
            'version' => '2.0.7.0',
            'reference' => 'ce45c16d4fbbe7d1c516d8d0e8311e07f6138eed',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-jui',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yiisoft/yii2-swiftmailer' => array(
            'pretty_version' => '2.1.3',
            'version' => '2.1.3.0',
            'reference' => '7b7ec871b4a63c0abbcd10e1ee3fb5be22f8b340',
            'type' => 'yii2-extension',
            'install_path' => __DIR__ . '/../yiisoft/yii2-swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
